name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 3.1.3
homepage: https://github.com/martin-braun-net/google_maps_place_picker_mb

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  google_api_headers: ^4.4.2
  google_maps_flutter: ^2.10.1
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.3.0
  provider: ^6.1.2
  tuple: ^2.0.2
  uuid: ^4.5.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift